name: PR Checks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: git clean -ffdx  
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci

  preview:
    name: Preview Deployment
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write
    environment:
      name: preview
      url: https://colemanswe.github.io/previews/pr-${{ github.event.number }}/
    steps:
      - uses: actions/checkout@v4
        with:
          repository: colemanswe/hsl-live-tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          VITE_BASE_URL: '/previews/pr-${{ github.event.number }}/'
      - name: Prepare artifact
        run: |
          touch dist/.nojekyll  # Required for GitHub Pages
          echo "Built: $(date)" > dist/deployment-info.txt
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/  # Explicit path to build directory
          retention-days: 1  # Auto-cleanup old previews
      - uses: actions/deploy-pages@v4
      - name: Create Preview Comment
        uses: actions/github-script@v7
        with:
          script: |
            const url = `https://colemanswe.github.io/previews/pr-${{ github.event.number }}/`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment available at: [${url}](${url})`
            })

      - name: Report Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { job, conclusion } = context.payload.workflow_run || {};
            if (conclusion === 'failure') {
              core.setFailed('Tests must pass before merging');
            } 