name: PR Checks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number to test'
        required: true
        type: number

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: git clean -ffdx  
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
      - name: Add routing support
        run: |
          echo '<script>window.location.replace(window.location.pathname + "index.html")</script>' > dist/redirect.html
          cp dist/index.html dist/404.html
      - uses: actions/upload-pages-artifact@v3

  preview:
    name: Preview Deployment
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build with base path
        run: |
          npm ci
          npm run build
        env:
          VITE_BASE_URL: '/hsl-live-tracker/previews/pr-${{ github.event.number }}/'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
          destination_dir: hsl-live-tracker/previews/pr-${{ github.event.number }}
          force_orphan: true
          keep_files: false

      - name: Create comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAGES_TOKEN }}
          script: |
            const url = `https://colemanswe.github.io/hsl-live-tracker/previews/pr-${{ github.event.number }}/`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview: [${url}](${url})`
            })

      - name: Report Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { job, conclusion } = context.payload.workflow_run || {};
            if (conclusion === 'failure') {
              core.setFailed('Tests must pass before merging');
            } 